version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    hostname: pidock
    environment:
      TZ: 'America/Edmonton'
      WEBPASSWORD: 'shareen2'
    volumes:
       - '/opt/buddy-nfs/pihole/etc-pihole/:/etc/pihole/'
       - '/opt/buddy-nfs/pihole/etc-dnsmaq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.routers.pihole.rule=Host(`ph2.home.truecool.com`)"
      - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pihole.middlewares=pihole-https-redirect"
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.rule=Host(`ph2.home.truecool.com`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
