version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: '10m'
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=mpzarde@truecool.com
      - CF_API_KEY=d5feacd52ecef4f4678cff2189062b05c3b08
      # - CF_API_KEY=YOUR_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/mpzarde/docker/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/mpzarde/docker/traefik/data/acme.json:/acme.json
      - /home/mpzarde/docker/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.home.truecool.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=mpzarde:$$apr1$$pVfPutBO$$McQ2.BLcV8lPHAW/6HJuu1"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.home.truecool.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=home.truecool.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.home.truecool.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
