version: '3.3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    container_name: orbital_sync
    restart: unless-stopped
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.34:8080'
      PRIMARY_HOST_PASSWORD: 'shareen2'
      SECONDARY_HOST_1_BASE_URL: 'https://ph2.home.truecool.com'
      SECONDARY_HOST_1_PASSWORD: 'shareen2'
      INTERVAL_MINUTES: 30
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
