version: '3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    container_name: orbital_sync
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.34:8080'
      PRIMARY_HOST_PASSWORD: 'shareen2'
      SECONDARY_HOST_1_BASE_URL: 'https://pihole.home.truecool.com'
      SECONDARY_HOST_1_PASSWORD: 'shareen2'
      INTERVAL_MINUTES: 30
